In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
print(a)

[1 2 3]


In [25]:
b = np.array([[2.,3.,4.],[5.,6.,7.]])
print(b)

[[2. 3. 4.]
 [5. 6. 7.]]


In [15]:
a.ndim
b.ndim

2

In [17]:
a.ndim

1

In [19]:
a.shape

(3,)

In [21]:
b.shape

(2, 3)

In [23]:
a.dtype

dtype('int32')

In [27]:
b.dtype

dtype('float64')

In [29]:
a.itemsize

4

In [31]:
a.size

3

In [33]:
a.nbytes

12

In [35]:
b.itemsize

8

In [37]:
b.size

6

In [39]:
b.nbytes

48

In [41]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [43]:
a[1,2]

13

In [45]:
a[0,-3]

8

In [47]:
a[0,:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
a[1,:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
a[0,0:-1:2]

array([1, 3, 5, 7, 9])

In [57]:
a[1,1] = 100
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11 100  13  14  15  16  17  18  19  20]]


In [61]:
a[:,2] = [1,2]
print(a)

[[  1   2   1   4   5   6   7   8   8  10]
 [ 11 100   2  14  15  16  17  18   8  20]]


In [63]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [65]:
a[1,0,1]

8

In [69]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [73]:
np.full((3,3),28)

array([[28, 28, 28],
       [28, 28, 28],
       [28, 28, 28]])